# Setup data volumes
data:
    image: busybox:latest
    volumes:
        - /data
        - /var/lib/postgresql/data
    entrypoint: /bin/echo


# Setup databases required by sentry
postgres:
    image: postgres:9.4
    environment:
        - POSTGRES_USER:sentry
        - POSTGRES_PASSWORD:sentry
    volumes_from:
        - data

redis:
    image: redis:latest
    volumes_from:
        - data


# Setup sentry itself
sentry:
    image: sentry:latest
    links:
        - redis
        - postgres
    ports:
        - 9000:9000
    stdin_open: true
    tty: true
    env_file:
        environment.sh


# Setup the workers sentry needs
sentry_celery_beat:
    image: sentry:latest
    links:
        - redis
        - postgres
    command: "sentry celery beat"
    env_file:
        environment.sh

sentry_celery_worker:
    image: sentry:latest
    links:
        - redis
        - postgres
    command: "sentry celery worker"
    env_file:
        environment.sh
